// Style C, "snowbound north": 32 px, bundled up in fur-collared parkas, mittens and
// fur-topped boots, round faces with rosy cheeks. Shares the storybook head geometry
// (hair and hats), with its own face, torsos and chunkier legs.
import { pm } from './px.js';
import { A } from './people-a.js';

// The northern boots are two rows taller: take the storybook legs and thicken the boots,
// with a light fur band at the top of the near boot.
function tallBoots(rows) {
  const t = rows.slice(0, 5), b = rows.slice(5);
  const fur = b[0].replace(/B/g, 'b').replace(/D/g, 'D');
  return [...t, fur, b[0], b[1], b[2], b[2]];
}

export const C = {
  H: 32, W: 16, headTop: 2, hatTop: -2, torsoTop: 10, legsTop: 22, eyeRow: 5,
  head: pm('headC', `
................
................
.....SSSSSSS....
....SSSSSSSSS...
....SShSSSShS...
....SSESSSSES...
....sSESSSSESS..
....sKSSSSSKSSS.
....sSSSSSMMSs..
.....sSSSSSSs...
......sSSSSs....
.......sSSs.....`),
  hair: A.hair,
  hat: A.hat,
  torso: {
    down: pm('downC', `
................
................
....AAAAAAAAA...
...cAAAAAAAAAA..
..ccCCCCCCCCCcC.
..cccCCCCCCCCcC.
..cccCCCLCCCCcC.
..cccCCCCCCCCcC.
..cccCCCLCCCCcC.
..NNcCCCCCCCCNN.
....cCCCLCCCC...
....aAAAAAAAA...
....aAAAAAAAA...`),
    fwd: pm('fwdC', `
................
................
....AAAAAAAAA...
...cAAAAAAAAAA..
..ccCCCCCCCCCcC.
.cccCCCCCCCCC.cC
.cccCCCLCCCCC.cC
.cc.cCCCCCCCC.cC
NN..cCCCLCCCC.NN
....cCCCCCCCC...
....cCCCLCCCC...
....aAAAAAAAA...
....aAAAAAAAA...`),
    back: pm('backC', `
................
................
....AAAAAAAAA...
...cAAAAAAAAAA..
..ccCCCCCCCCCcC.
....cCCCCCCCcCC.
....cCCCLCCcCC..
....cCCCCCcCC...
....cCCCLCNN....
....cCCCCCCCC...
....cCCCLCCCC...
....aAAAAAAAA...
....aAAAAAAAA...`),
    raise: pm('raiseC', `
..............NN
..............cC
....AAAAAAAAA.cC
...cAAAAAAAAAAcC
..ccCCCCCCCCCcC.
..cccCCCCCCCC...
..cccCCCLCCCC...
..cccCCCCCCCC...
..cccCCCLCCCC...
..NNcCCCCCCCC...
....cCCCLCCCC...
....aAAAAAAAA...
....aAAAAAAAA...`),
    point: pm('pointC', `
................
................
....AAAAAAAAA...
...cAAAAAAAAAA..
..ccCCCCCCCCCccC
..cccCCCCCCCCCCN
..cccCCCLCCCC...
..cccCCCCCCCC...
..cccCCCLCCCC...
..NNcCCCCCCCC...
....cCCCLCCCC...
....aAAAAAAAA...
....aAAAAAAAA...`),
    carry: pm('carryC', `
................
................
....AAAAAAAAA...
...cAAAAAAAAAA..
..ccCCCCCCCCCcC.
....cCCCCCCCCcC.
....cCCCLCCCCcC.
....cCCCCCCCCccC
....cCCCLCCCCNNN
....cCCCCCCCC...
....cCCCLCCCC...
....aAAAAAAAA...
....aAAAAAAAA...`),
  },
  legs: {
    stand: tallBoots(A.legs.stand),
    walk: A.legs.walk.map(tallBoots),
    seated: tallBoots(A.legs.seated),
  },
  walkBob: [0, 1, -1, 0, 1, -1],
  walkArm: ['back', 'back', 'down', 'fwd', 'fwd', 'down'],
  apron: A.apron,
  scarf: { top: 11, map: pm('scarfC', `
.....RRRRRRR....
....RRrRRRRRRr..
....RRRR....RRr.
....RRr.........
....rr..........`) },
  beard: A.beard,
  glasses: { top: 4, map: pm('glassesC', `
.....GGG..GGG...
.....G.GGGG.G...
.....G.G..G.G...
.....GGG..GGG...`) },
  stubble: A.stubble,
  blink: { top: 5, map: pm('blinkC', `
......S....S....
......h....h....`) },
  kid: A.kid,
  sleeper: A.sleeper,
};
