// Style B, "moody harbour": tall, lean people, 36 px, small heads, long coats and
// heavy boots, three-quarter view facing right. Same keys and layers as people-a.js.
import { pm } from './px.js';
import { A } from './people-a.js';

export const B = {
  H: 36, W: 16, headTop: 2, hatTop: -2, torsoTop: 11, legsTop: 25, eyeRow: 6,
  head: pm('headB', `
................
................
......SSSSSS....
.....SSSSSSSS...
.....SSSSSSSS...
.....SShSSShS...
.....sSESSSES...
.....sSSSSSSSS..
.....sSSSSSSSs..
......sSSSSMs...
.......sSSSs....
........sSs.....
........sSs.....`),
  hair: {
    short: pm('shortB', `
......HHHHHH....
.....HHHHHHHH...
....HHHHHHHHHH..
....HHhHHHHHHH..
....HHH.....HH..
....HHh.........
....hHh.........
.....h..........`),
    bun: pm('bunB', `
......HHHHHH....
.....HHHHHHHH...
....HHHHHHHHHH..
...HHHhHHHHHHH..
..HHHHH.....HH..
..HHHHh.........
...hhHh.........
.....h..........`),
    long: pm('longB', `
......HHHHHH....
.....HHHHHHHH...
....HHHHHHHHHH..
....HHhHHHHHHH..
...HHHH.....HH..
...HHHh.........
...HHHh.........
...HHHh.........
...HHHh.........
...HHHh.........
...HHHh.........
...HHhh.........
...HHh..........
...hh...........`),
    curls: pm('curlsB', `
.....HH.HH.HH...
....HHHHHHHHHH..
...HHHHHHHHHHHH.
...HHhHHHHHHHHH.
...HHHH....HHH..
...HHHh......H..
....HHh.........
....hh..........`),
    bald: pm('baldB', `
................
................
................
................
.....h..........
....HH..........
....HH..........
.....h..........`),
    tuft: pm('tuftB', `
........HH......
......HHHHHH....
.....HHHHHHHH...
....HHHHHHHHHH..
....HHh.....HH..
....HHh.........
....hHh.........
.....h..........`),
  },
  hat: {
    cap: pm('capB', `
................
................
......NNNNNN....
.....NNNNNNNN...
....NNNNNNNNNN..
....nNnnnnnnNNNN
...............n
................`),
    brim: pm('brimB', `
.......NNNNN....
......NNNNNNN...
......NNnNNNN...
......NNNNNNN...
...NNNNNNNNNNNN.
...nnnnnnnnnnnn.
................
................`),
    beanie: pm('beanieB', `
........NN......
......NNNNNN....
.....NNNNNNNN...
....NNNNNNNNNN..
....NnNNNNNNNN..
....nnnnnnnnnn..
....nnn.....nn..
................`),
    kerchief: pm('kerchiefB', `
................
................
......NNNNNN....
.....NNNNNNNN...
....NNNNNNNNNN..
...NNnNNNNNNNN..
..NNNN..........
...NN...........`),
    souwester: pm('souwesterB', `
................
.......NNNNN....
......NNNNNNN...
.....NNNNNNNNN..
....NNNNNNNNNNN.
...NNnnnnnnnnnn.
..NNN...........
..nn............`),
    bonnet: pm('bonnetB', `
................
................
......NNNNNN....
.....NNNNNNNN...
....NNNNNNNNNN..
....NNnNNNNNNN..
....NN..........
....NN..........`),
    flatcap: pm('flatcapB', `
................
................
.....NNNNNNNNN..
....NNNNNNNNNN..
....NNNNNNNNNNNN
....nnnnnnnnnnNN
................
................`),
    fur: pm('furB', `
.....NNNNNNNN...
....NNNNNNNNNN..
....NNNNNNNNNN..
...nNNNNNNNNNNn.
...nnnnnnnnnnnn.
...nn........nn.
...nn........nn.
...n..........n.`),
    hood: pm('hoodB', `
......NNNNNN....
.....NNNNNNNN...
....NNNNNNNNNN..
...NNNNNNNNNNNN.
...NNAAAAAAAANN.
...NA........AN.
...NA........AN.
...NA........AN.
...NA........AN.
...NA...........
...NA........AN.
...NNA......ANN.
...NNAA....AANN.
....NNAAAAAANN..
.....NNNNNNNN...`),
  },
  // long coat with a belt line; the last row is the spare hem for the walk bob
  torso: {
    down: pm('downB', `
................
................
......CCACC.....
.....CCCACCC....
....cCCCCCCCcC..
...ccCCCCCCCcC..
...cccCCCCCCcC..
...cccCCLCCCcC..
...cccCCCCCCcC..
...cccCCLCCCcC..
...cccCCCCCCcC..
...ssccCCCCCss..
.....cCCLCCC....
.....cCCCCCC....
.....cCCCCCC....`),
    fwd: pm('fwdB', `
................
................
......CCACC.....
.....CCCACCC....
....cCCCCCCCcC..
...ccCCCCCCCcC..
...ccCCCCCCC.cC.
..cccCCLCCCC.cC.
..cccCCCCCCC..cC
..cc.cCCLCCC..cC
.ss..cCCCCCC..ss
.....cCCCCCC....
.....cCCLCCC....
.....cCCCCCC....
.....cCCCCCC....`),
    back: pm('backB', `
................
................
......CCACC.....
.....CCCACCC....
....cCCCCCCCcC..
.....cCCCCCCcC..
.....cCCCCCcCC..
.....cCCLCcCC...
.....cCCCCcCC...
.....cCCLcCC....
.....cCCCcss....
.....cCCCCCC....
.....cCCLCCC....
.....cCCCCCC....
.....cCCCCCC....`),
    raise: pm('raiseB', `
.............ss.
.............cC.
......CCACC..cC.
.....CCCACCC.cC.
....cCCCCCCCcC..
...ccCCCCCCC....
...cccCCCCCC....
...cccCCLCCC....
...cccCCCCCC....
...cccCCLCCC....
...cccCCCCCC....
...sscCCCCCC....
.....cCCLCCC....
.....cCCCCCC....
.....cCCCCCC....`),
    point: pm('pointB', `
................
................
......CCACC.....
.....CCCACCC....
....cCCCCCCCccCC
...ccCCCCCCCCCCs
...cccCCCCCC....
...cccCCLCCC....
...cccCCCCCC....
...cccCCLCCC....
...cccCCCCCC....
...sscCCCCCC....
.....cCCLCCC....
.....cCCCCCC....
.....cCCCCCC....`),
    carry: pm('carryB', `
................
................
......CCACC.....
.....CCCACCC....
....cCCCCCCCcC..
.....cCCCCCCcC..
.....cCCCCCCcC..
.....cCCLCCCcC..
.....cCCCCCCcCC.
.....cCCLCCCCccC
.....cCCCCCCCsss
.....cCCCCCC....
.....cCCLCCC....
.....cCCCCCC....
.....cCCCCCC....`),
  },
  legs: {
    stand: pm('standB', `
.....uuutTTT....
.....uuutTTT....
.....uuutTTT....
.....uuutTTT....
.....uuutTTT....
.....uuutTTT....
.....uuutTTT....
.....uuutTTT....
.....DDDBBBB....
.....DDDbBBBBB..
.....DDDBBBBBB..`),
    walk: [pm('wB0', `
.....uuutTTT....
....uuuu.tTTT...
....uuu..tTTTT..
...uuu....tTTT..
...uuu.....TTT..
..uuu......TTTT.
..uuu.......TTT.
.uuu........TTTT
.DDD........BBBB
DDDD........BBB.
..DDD.......BB..`), pm('wB1', `
.....uuutTTT....
.....uuu.tTTT...
....uuu..tTTT...
....uuu...TTTT..
...uuu....TTTT..
...uuu.....TTT..
...uuu.....TTT..
..uuu......TTTT.
..DDD......BBBB.
..DDDD.....BBBBB
...DDD.....BBBB.`), pm('wB2', `
.....uuutTTT....
.....uuutTTT....
....uuuu.tTTT...
...uuuu..tTTT...
..uuuu...tTTT...
..uuu....tTTT...
.uuuu....tTTT...
.uuuu....tTTT...
.DDDD....BBBB...
DDDD.....bBBBBB.
.........BBBBBB.`), pm('wB3', `
.....uuutTTT....
......utTTT.....
......tTTTu.....
.....tTTT.uu....
....tTTT..uuu...
...tTTT...uuu...
..tTTT.....uuu..
.tTTT......uuu..
.BBBB.......DDDD
BBBB........DDD.
..BBB.......DD..`), pm('wB4', `
.....uuutTTT....
......tTTTu.....
......tTTTuu....
.....tTTT.uuu...
.....tTTT.uuu...
....tTTT..uuu...
....tTTT...uuu..
...tTTT....uuu..
...BBBB....DDDD.
..BBBBB....DDDDD
...BBBB.....DDD.`), pm('wB5', `
.....uuutTTT....
.....uuutTTTT...
.....uuu.tTTTT..
.....uuu..tTTTT.
.....uuu...tTTT.
.....uuu....TTT.
.....uuu....TTTT
.....uuu....BBBB
.....DDD....bBBB
.....DDD........
.....DDDD.......`)],
    seated: pm('seatedB', `
.....uuuTTTTTT..
.....uuutTTTTTT.
...........tTTT.
...........tTTT.
...........tTTT.
...........tTTT.
...........tTTT.
...........tTTT.
...........BBBB.
...........BBBBB
...........BBBBB`),
  },
  walkBob: [0, 1, -1, 0, 1, -1],
  walkArm: ['back', 'back', 'down', 'fwd', 'fwd', 'down'],
  apron: { top: 16, map: pm('apronB', `
........AA......
.......AAAA.....
......aAAAAA....
......aAAAAA....
......aAAAAA....
......aAAAAAA...
......aAAAAAA...
.....aAAAAAAA...
.....aAAAAAAA...
.....aAAAAAAA...
.....aAAAAAAA...
.....aAAAAAAA...
.....aaaaaaaa...`) },
  scarf: { top: 11, map: pm('scarfB', `
.......RRRRR....
......RRrRRRR...
.....RRRR..RRRr.
.....RRR........
.....rr.........`) },
  beard: { top: 8, map: pm('beardB', `
.....HHHHHHHHH..
.....HHHHHHHHH..
......HHhHHHH...
......hHHHHh....
.......hhhh.....`) },
  glasses: { top: 5, map: pm('glassesB', `
......GGG.GGG...
......G.GGG.G...
......GGG.GGG...`) },
  stubble: { top: 8, map: pm('stubbleB', `
......jjjjjjjj..
......jjjjjMj...
.......jjjjj....`) },
  blink: { top: 6, map: pm('blinkB', `
.......h...h....`) },
  kid: {
    H: 22, W: 12, hatTop: -3, hairTop: -1, raiseTop: 7,
    body: pm('kidB', `
....SSSSSS..
...SSSSSSSS.
...SSSSSSSS.
...SShSSShS.
...sSESSSES.
...sSSSSSSSS
...sSSSSMSs.
....sSSSSs..
.....sSSs...
....CCCACC..
...cCCCCCCc.
...cCCCCCCC.
...cCCLCCCC.
...cCCCCCCC.
...ssCCCCss.
....uuutTT..
....uuutTT..
....uuutTT..
....uuutTT..
....uuutTT..
....DDDBBBB.
....DDDBBBBB`),
    raise: pm('kidraiseB', `
..........ss
..........cC
....CCCACCcC
...cCCCCCCC.
...cCCCCCCC.
...cCCLCCCC.
...cCCCCCCC.
...ss.CCCC..`),
    hair: A.kid.hair,
  },
  sleeper: pm('sleeperB', `
..HHHHHH........
.HHHHHHHH.......
.HHhSSSSSS......
.HHSSSSSSSS.....
.HHSShSSShS.....
..hSShSSShS.....
...sSSSSSSSS....
...sSSSSSMs.....
....sSSSSs......
.....ssss.......`),
};
