// Style A, "cosy storybook": stocky people, 28 px tall, big heads and big eyes, seen in
// three-quarter view facing right. Every map is 16 wide; the feet stand on the last row
// (row 27). Keys — S/s skin, E eye, W eye white, K cheek, M mouth, H/h hair, C/c/L coat,
// T/t near trouser, u far trouser, B/b near boot, D far boot, A/a apron, N/n hat,
// R/r scarf, G glasses, j stubble.
import { pm } from './px.js';

export const A = {
  H: 28, W: 16, headTop: 2, hatTop: -2, torsoTop: 10, legsTop: 20, eyeRow: 5,
  // three-quarter head: round skull, far ear, big eyes with a highlight, a nose bump on the near side
  head: pm('head', `
................
................
.....SSSSSSS....
....SSSSSSSSS...
....SShhSSShhS..
....SSWESSWESS..
....sSEESSEESS..
....sKSSSSSKSSS.
....sSSSSSMMSs..
.....sSSSSSSs...
......sSSSSs....
.......sSSs.....`),
  hair: {
    short: pm('short', `
.....HHHHHHH....
....HHHHHHHHH...
...HHHHHHHHHHH..
...HHhHHHHHHHH..
...HHH......HH..
...HHh..........
...hHh..........
....h...........`),
    bun: pm('bun', `
.....HHHHHHH....
....HHHHHHHHH...
...HHHHHHHHHHH..
..HHHhHHHHHHHH..
.HHHHH......HH..
.HHHHh..........
..hhHh..........
....h...........`),
    long: pm('long', `
.....HHHHHHH....
....HHHHHHHHH...
...HHHHHHHHHHH..
...HHhHHHHHHHH..
..HHHH......HH..
..HHHh..........
..HHHh..........
..HHHh..........
..HHHh..........
..HHHh..........
..HHhh..........
..HHh...........
..hh............`),
    curls: pm('curls', `
....HH.HHH.HH...
...HHHHHHHHHHH..
..HHHHHHHHHHHHH.
..HHhHHHHHHHHHH.
..HHHH.....HHH..
..HHHh.......H..
...HHh..........
...hh...........`),
    bald: pm('bald', `
................
................
................
................
....h...........
...HH...........
...HH...........
....h...........`),
    tuft: pm('tuft', `
.......HH.......
.....HHHHHH.....
....HHHHHHHHH...
...HHHHHHHHHHH..
...HHh......HH..
...HHh..........
...hHh..........
....h...........`),
  },
  // hats sit two rows above the figure box
  hat: {
    cap: pm('cap', `
................
................
.....NNNNNNN....
....NNNNNNNNN...
...NNNNNNNNNNN..
...nNnnnnnnnNNNN
...............n
................`),
    brim: pm('brim', `
......NNNNNN....
.....NNNNNNNN...
.....NNnNNNNN...
.....NNNNNNNN...
..NNNNNNNNNNNNN.
..nnnnnnnnnnnnn.
................
................`),
    beanie: pm('beanie', `
.......NN.......
.....NNNNNN.....
....NNNNNNNN....
...NNNNNNNNNN...
...NnNNNNNNNNN..
...nnnnnnnnnnn..
...nnn......nn..
................`),
    kerchief: pm('kerchief', `
................
................
.....NNNNNNN....
....NNNNNNNNN...
...NNNNNNNNNNN..
..NNnNNNNNNNNN..
.NNNN...........
..NN............`),
    souwester: pm('souwester', `
................
......NNNNN.....
.....NNNNNNN....
....NNNNNNNNN...
...NNNNNNNNNNNN.
..NNnnnnnnnnnnn.
.NNN............
.nn.............`),
    bonnet: pm('bonnet', `
................
................
.....NNNNNNN....
....NNNNNNNNN...
...NNNNNNNNNNN..
...NNnNNNNNNNN..
...NN...........
...NN...........`),
    flatcap: pm('flatcap', `
................
................
....NNNNNNNNNN..
...NNNNNNNNNNN..
...NNNNNNNNNNNNN
...nnnnnnnnnnnNN
................
................`),
    hood: pm('hood', `
.....NNNNNNN....
....NNNNNNNNN...
...NNNNNNNNNNN..
..NNNNNNNNNNNNN.
..NNAAAAAAAAANN.
..NA.........AN.
..NA.........AN.
..NA.........AN.
..NA.........AN.
..NA............
..NA.........AN.
..NNA.......ANN.
..NNAA.....AANN.
...NNAAAAAAANN..
....NNNNNNNNN...`),
    fur: pm('fur', `
....NNNNNNNNN...
...NNNNNNNNNNN..
...NNNNNNNNNNN..
..nNNNNNNNNNNNn.
..nnnnnnnnnnnnn.
..nn.........nn.
..nn.........nn.
..n...........n.`),
  },
  // torsos start at row 10 so a raised arm has room; the last row is a spare hem that
  // fills the gap when the body bobs up in the walk
  torso: {
    down: pm('down', `
................
................
.....CCCACCC....
....CCCCACCCC...
...cCCCCCCCCCcC.
..ccCCCCCCCCCcC.
..cccCCCCCCCCcC.
..cccCCCLCCCCcC.
..cccCCCCCCCCcC.
..sscCCCLCCCCss.
....cCCCCCCCC...`),
    fwd: pm('fwd', `
................
................
.....CCCACCC....
....CCCCACCCC...
...cCCCCCCCCCcC.
..ccCCCCCCCCCcC.
.cccCCCCCCCCC.cC
.cccCCCLCCCCC.cC
.ss.cCCCCCCCC.ss
....cCCCLCCCC...
....cCCCCCCCC...`),
    back: pm('back', `
................
................
.....CCCACCC....
....CCCCACCCC...
...cCCCCCCCCCcC.
....cCCCCCCCcCC.
....cCCCCCCcCC..
....cCCCLCcCC...
....cCCCCCcss...
....cCCCLCCC....
....cCCCCCCC....`),
    raise: pm('raise', `
..............ss
..............cC
.....CCCACCC..cC
....CCCCACCCC.cC
...cCCCCCCCCCcC.
..ccCCCCCCCCC...
..cccCCCCCCCC...
..cccCCCLCCCC...
..cccCCCCCCCC...
..sscCCCLCCCC...
....cCCCCCCCC...`),
    point: pm('point', `
................
................
.....CCCACCC....
....CCCCACCCC...
...cCCCCCCCCCccC
..ccCCCCCCCCCCCs
..cccCCCCCCCC...
..cccCCCLCCCC...
..cccCCCCCCCC...
..sscCCCLCCCC...
....cCCCCCCCC...`),
    carry: pm('carry', `
................
................
.....CCCACCC....
....CCCCACCCC...
...cCCCCCCCCCcC.
....cCCCCCCCCcC.
....cCCCCCCCCcC.
....cCCCLCCCCccC
....cCCCCCCCCsss
....cCCCLCCCC...
....cCCCCCCCC...`),
  },
  // six-frame walk: contact, recoil, passing (back foot lifted), contact, recoil, passing
  // (front knee up). Feet always reach the last row unless lifted.
  legs: {
    stand: pm('stand', `
....uuuutTTTT...
....uuuutTTTT...
....uuuutTTTT...
....uuuutTTTT...
....uuuutTTTT...
....DDDDBBBBB...
....DDDDbBBBBB..
....DDDDBBBBBB..`),
    walk: [pm('w0', `
....uuuutTTTT...
...uuuu.tTTTTT..
...uuu...tTTTT..
..uuu.....TTTT..
..uuu......TTTT.
.DDD.......BBBBB
.DDDD.......BBBB
..DDD.......BBB.`), pm('w1', `
....uuuutTTTT...
....uuu.tTTTT...
...uuu...TTTT...
...uuu...TTTTT..
..uuu.....TTTT..
..DDD.....BBBBB.
..DDDD....BBBBBB
...DDD....BBBBB.`), pm('w2', `
....uuuutTTTT...
....uuuutTTTT...
...uuuu.tTTTT...
..uuuu..tTTTT...
.uuuu...tTTTT...
.DDDD...BBBBB...
DDDD....bBBBBB..
........BBBBBB..`), pm('w3', `
....uuuutTTTT...
.....uuutTTTT...
......tTTTTu....
.....tTTT.uuuu..
...tTTT...uuuu..
..BBBB.....DDDDD
.BBBBB......DDDD
..BBB.......DDD.`), pm('w4', `
....uuuutTTTT...
.....uutTTTT....
.....tTTTTuu....
....tTTT..uuu...
...tTTT...uuu...
..BBBBB...DDDDD.
.BBBBBB...DDDDD.
..BBBBB....DDD..`), pm('w5', `
....uuuutTTTT...
....uuuutTTTTT..
....uuuu.tTTTTT.
....uuuu...TTTT.
....uuuu...BBBBB
....DDDD...bBBBB
....DDDD........
....DDDDD.......`)],
    // sitting: thighs forward, shins down, feet on the floor (row 27)
    seated: pm('seated', `
....uuuTTTTTT...
....uuuutTTTTT..
..........tTTT..
..........tTTT..
..........tTTT..
..........BBBB..
..........BBBBB.
..........BBBBB.`),
  },
  walkBob: [0, 1, -1, 0, 1, -1],
  walkArm: ['back', 'back', 'down', 'fwd', 'fwd', 'down'],
  // overlays: apron (rows 13..23), scarf (11..14), beard (8..11), glasses (5..7), stubble (8..10)
  apron: { top: 13, map: pm('apron', `
.......AA.......
......AAAA......
.....aAAAAA.....
.....aAAAAA.....
.....aAAAAAA....
.....aAAAAAA....
....aAAAAAAA....
....aAAAAAAAA...
....aAAAAAAAA...
....aAAAAAAAA...
....aaaaaaaaa...`) },
  scarf: { top: 11, map: pm('scarf', `
.....RRRRRRR....
....RRrRRRRRRr..
....RRR.....RR..
....rr..........`) },
  beard: { top: 8, map: pm('beard', `
....HHHHHHHHHH..
....HHHHHHHHHH..
.....HHhHHHHH...
......hhhhhh....`) },
  glasses: { top: 4, map: pm('glasses', `
......GG..GG....
.....G..GG..G...
.....G..G.G.G...
......GG..GG....`) },
  blink: { top: 5, map: pm('blink', `
......SS..SS....
......hh..hh....`) },
  stubble: { top: 8, map: pm('stubble', `
.....jjjjjMMjj..
.....jjjjjjjj...
......jjjjjj....`) },
  // a child: 18 px, big head, short legs; arm variants down/raise
  kid: {
    H: 18, W: 12, hatTop: -3, hairTop: -1, raiseTop: 7,
    body: pm('kid', `
....SSSSSS..
...SSSSSSSS.
...SShhSShhS
...SSWESSWES
...sSEESSEES
...sKSSSSKSS
...sSSSSMMSs
....sSSSSSs.
.....sSSs...
....CCCACC..
...cCCCCCCc.
...cCCCCCCC.
...ssCLCCss.
....uuutTT..
....uuutTT..
....uuutTT..
....DDDBBBB.
....DDDBBBBB`),
    raise: pm('kidraise', `
..........ss
..........cC
....CCCACCcC
...cCCCCCCC.
...cCCCCCCC.
...ss.CLCC..`),
    hair: pm('kidhair', `
....HHHHHH..
...HHHHHHHH.
..HHHHHHHHHH
..HHhHHHHHHH
..HHH.......
..hHh.......
...h........`),
  },
  // lying in bed: head on the pillow, closed eyes, the blanket drawn by the room
  sleeper: pm('sleeper', `
..HHHHHHH.......
.HHHHHHHHH......
.HHhSSSSSSS.....
.HHSSSSSSSSS....
.HHSShSSShSS....
..hSShhSShhS....
...sSSSSSSSSS...
...sSSSSSMSs....
....sSSSSSs.....
.....ssss.......`),
};

export const CAT = {
  frames: [pm('cat0', `
.F.F...........
.FFFF..........
.FFfF........F.
..FFFFFFFFF..F.
..FFFFFFFFFFFF.
..FFFFFFFFFFF..
..FF.FF..FF.FF.
..ff.ff..ff.ff.`), pm('cat1', `
.F.F...........
.FFFF..........
.FFfF.......F..
..FFFFFFFFF.F..
..FFFFFFFFFFF..
..FFFFFFFFFFF..
..FF.FF..FF.FF.
..ff.ff..ff.ff.`)],
  sit: pm('catsit', `
.F.F.......
.FFFF......
.FFfF......
..FFFF.....
..FFFFF..F.
..FFFFFFFF.
..FFFFFFF..
..FF.FF....
..ff.ff....`),
};
export const DOG = {
  frames: [pm('dog0', `
.FF.............
.FFFF..........F
.FFff.........FF
..FFFFFFFFFFFFF.
..FFFFFFFFFFFF..
..FFFFFFFFFFFF..
..FFF.FF..FF.FF.
..fff.ff..ff.ff.`), pm('dog1', `
.FF............F
.FFFF.........FF
.FFff.........F.
..FFFFFFFFFFFFF.
..FFFFFFFFFFFF..
..FFFFFFFFFFFF..
..FFF.FF..FF.FF.
..fff.ff..ff.ff.`)],
};
export const GULL = {
  frames: [pm('gull0', `
....WWW....
...WWEWWYY.
....WWW....
gggWWWWW...
.ggggWWWWW.
..gggWWW...
....W.W....
....Y.Y....`)],
};
